### ISSUE TITLE
Não conseguir fazer rodar

### ISSUE THREAD

**Issue by abrahampe** [HenriqueTardivo/xml_to_danfe_dacte#2]
Se possível coloca as instruções no README de como fazer rodar, tentei rodar com ` yarn dev:server` mas deu erro:

`[INFO] 11:56:01 ts-node-dev ver. 1.1.8 (using ts-node ver. 9.1.1, typescript ver. 4.9.5)
Debugger listening on ws://127.0.0.1:9229/1cf51825-c4b1-4693-8a30-87f93f0a59c5
For help, see: https://nodejs.org/en/docs/inspector
Error: Cannot find module '../../../../application/modules/XMLtoPDF/UseCase/json-to-danfe-use-case'
Require stack:
- C:\projetos\nfe\xml_to_danfe_dacte\src\shared\infra\http\controllers\danfe.controller.ts
- C:\projetos\nfe\xml_to_danfe_dacte\src\shared\infra\http\routes\index.ts
- C:\projetos\nfe\xml_to_danfe_dacte\src\shared\infra\http\server.ts
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\projetos\nfe\xml_to_danfe_dacte\src\shared\infra\http\controllers\danfe.controller.ts:5:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Module._compile (C:\projetos\nfe\xml_to_danfe_dacte\node_modules\source-map-support\source-map-support.js:568:25)
    at Module.m._compile (C:\Users\ABRAOP~1\AppData\Local\Temp\ts-node-dev-hook-5462477836956359.js:69:33)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at require.extensions.<computed> (C:\Users\ABRAOP~1\AppData\Local\Temp\ts-node-dev-hook-5462477836956359.js:71:20)
[ERROR] 11:56:02 Error: Cannot find module '../../../../application/modules/XMLtoPDF/UseCase/json-to-danfe-use-case'
Require stack:
- C:\projetos\nfe\xml_to_danfe_dacte\src\shared\infra\http\controllers\danfe.controller.ts
- C:\projetos\nfe\xml_to_danfe_dacte\src\shared\infra\http\routes\index.ts
- C:\projetos\nfe\xml_to_danfe_dacte\src\shared\infra\http\server.ts`

**Comment by HenriqueTardivo** [comment]
Boa tarde, tenta clonar novamente e rodar agora, mudei a branch principal para a versão estável.

Para rodar execute 
`yarn`

`yarn start:dev`

A branch principal que estava anteriormente ainda esta em desenvolvimento, estou refatorando alguns modulos para typescript.

**Comment by arthurmdros** [comment]
Ele fica reclamando que não conseguiu baixar as dependências e não encontra um package.json, apesar de ao rodar yarn deveria instalar as dependencias

**Comment by HenriqueTardivo** [comment]
@arthurmdros Tenta clonar novamente e fazer yarn e depois yarn dev:server

**Comment by arthurmdros** [comment]
@HenriqueTardivo Blz consegui baixar as dependencias certin e rodei o script para a API, porém gerou esse erro e não conectou a API na porta 3000:

TypeError: (0 , express_1.default) is not a function
    at Object.<anonymous> (/home/gabriel/workspace/PersonalProjects/Angular_projects/xml_to_danfe_dacte/src/shared/infra/http/server.ts:7:20)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Module._compile (/home/gabriel/workspace/PersonalProjects/Angular_projects/xml_to_danfe_dacte/node_modules/source-map-support/source-map-support.js:568:25)
    at Module.m._compile (/tmp/ts-node-dev-hook-1302478211311171.js:69:33)
    at Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at require.extensions.<computed> (/tmp/ts-node-dev-hook-1302478211311171.js:71:20)
    at Object.nodeDevHook [as .ts] (/home/gabriel/workspace/PersonalProjects/Angular_projects/xml_to_danfe_dacte/node_modules/ts-node-dev/lib/hook.js:63:13)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
[ERROR] 21:44:53 TypeError: (0 , express_1.default) is not a function

**Comment by arthurmdros** [comment]
@HenriqueTardivo Resolvido, era um detalhe de lint do meu VsCode

**Comment by HenriqueTardivo** [comment]
@arthurmdros Putz percebi um errão meu aqui, coloquei no gitignore '.json' ai acabou não subindo nenhum arquivo json pro git, por isso não tinha subido o package.json

Esse erro ai que vc mencionou é por causa do tsconfig.json, faz um git pull pra puxar esse arquivo acabei de subir aqui agora

Desculpe o transtorno

**Comment by arthurmdros** [comment]
@HenriqueTardivo Man consegui rodar aqui e instalar corretamente, teve uns problemas na hora de rodar, mas era com relação a config do meu vscode o lint dele. Agora o meu problema está sendo na resposta que estou recebendo pelo POSTMAN. Eu configurei o PARAMS para passar o nr_chacesso e o HEADERS com o content-type: text/plain, porém o retorno que ele me dá é a messagem:

{
    "message": "XML da nota é invalido"
}

Estou passando a chave de uma NFe válida que foi: 35180803102452000172550010000474281920007498
E eu consigo baixar ele pelo portal da NFe

**Comment by arthurmdros** [comment]
@HenriqueTardivo QUe nada man, precisa pedir desculpas não kkkkk voce ta me ajudando isso sim

**Comment by HenriqueTardivo** [comment]
Tem que passar o xml da nota no body, só com o xml não é possivel imprimir

**Comment by arthurmdros** [comment]
@HenriqueTardivo man, sei que só estou incomodando você, mas agora ele reclamou da timezone. Dai notei que é um arquivo q voce prepara para gerar o PDF sabe me dizer se falta instalar algo?

Erro:
"message": "Erro na requisição Error: Cannot find module './timezones/africa.json'
